import React from "react";
import DescargasUi from "./DescargasUi";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function page() {
  return(
    <>
      <DescargasUi/>
    </>
  )
}

