import React from 'react'
import NosotrosUi from './NosotrosUi'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
      <NosotrosUi/>
    </>
  )
}
