import React from 'react'
import ProfessionalsUi from './ProfessionalsUi'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <div>
      <ProfessionalsUi/>
    </div>
  )
}
