import { Plus_Jakarta_Sans,Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import LayoutWrapper from "./LayoutWrapper";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-plus-jakarta",
});

const satoshi = localFont({
  src: "../fonts/satoshi/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
  display: "swap",
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} ${inter.variable} ${satoshi.variable}`}
    >
      <body
        
      >
      <LayoutWrapper>
        {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
