import React from 'react'
import ProductosUi from './ProductosUi';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      <ProductosUi/>
    </div>
  )
}
